### ISSUE TITLE
BUG: Setting encoder to h264_nvenc throws out error

### ISSUE THREAD

**Issue by Gryxx** [davlee1972/upscale_video#23]
Sample video: https://ia801800.us.archive.org/30/items/big-buck-bunny-1440p-60-fps-vp-8/Big%20Buck%20Bunny%20480p%2030FPS.mp4

When trying to use -e h264_nvenc there is error in ffmpeg:
`[h264_nvenc @ 0x556070ed3b40] 10 bit encode not supported
[h264_nvenc @ 0x556070ed3b40] No capable devices found
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
`
I believe the ffmpeg command should be adjusted to not use 10bit profile in case of h264_nvenc.
The hevc_nvenc works fine, i didn't yet test VP9 on NVIDIA.

Below output of command when using all parameters as logged by upscale_video.py, just without the -loglevel option

https://pastebin.com/b7BJnFxW

**Comment by davlee1972** [comment]
I'll add a color bit parameter to the command line so you can choose what type of pixel format you want. Since 4K video files are much larger I was focusing on AV1 with p010le pixels for better compression results and didn't really test older H.264 and HEVC compression formats.

"Also at all points make sure you use p010le because it has a higher quality with a lower bitrate. With AV1 support for 10 bit is in the main branch which means there should not be a single client that can't play it."

https://www.reddit.com/r/handbrake/comments/123aivu/is_h265_10bit_worth_it_over_normal_h264/

**Comment by Gryxx** [comment]
The use case i found is to upscale very old sub 720p videos, the quality gets noticeably better when watching on 720p/1080p screen. This means that HEVC and 10bit color are bit of an overkill for the task. Especially since most devices i intend it to play the upscaled video support H.264 only.

**Comment by davlee1972** [comment]
Added --pix_fmt parameter to upscale_video.py

  -p, --pix_fmt PIX_FMT                 Pixel format used when merging frames into a video file. Default is p010le which is 10 bit color.
